name: Build V2rayU

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # CocoaPods 依赖（如果项目有 Podfile，否者可移除）
    - name: Install CocoaPods
      if: hashFiles('Podfile') != ''
      run: |
        which pod || sudo gem install cocoapods
        pod install

    - name: Show current directory and contents
      run: |
        pwd
        ls -l | cat -v
        ls | od -c
    
    - name: Ensure xcworkspace exists
      run: |
        pwd
        if [ ! -f "V2rayU.xcworkspace" ]; then
          echo "❌ V2rayU.xcworkspace not found! pod install did not succeed."
          exit 1
        fi

    # 构建 V2rayU（根据项目实际，优先用 xcworkspace，否则用 xcodeproj）
    - name: Build V2rayU
      run: |
        if [ -f "V2rayU.xcworkspace" ]; then
          xcodebuild -workspace V2rayU.xcworkspace -scheme V2rayU -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
        else
          xcodebuild -project V2rayU.xcodeproj -scheme V2rayU -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
        fi
      working-directory: ${{ github.workspace }}

    # 导出 .app 文件
    - name: Find built .app
      id: find_app
      run: |
        APP_PATH=$(find ~/Library/Developer/Xcode/DerivedData -type d -name "V2rayU.app" | head -n 1)
        if [ -z "$APP_PATH" ]; then
          echo "V2rayU.app not found"
          exit 1
        fi
        echo "app_path=$APP_PATH" >> $GITHUB_OUTPUT

    # 上传构建产物
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: V2rayU-app
        path: ${{ steps.find_app.outputs.app_path }}
